# Generated by Django 5.0.3 on 2024-03-25 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_userrank_quizsubmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizsubmission',
            old_name='scor',
            new_name='score',
        ),
    ]
